name: Generate Pacman Contribution Graph

on:
  # Запуск каждые 12 часов
  schedule:
    - cron: "0 */12 * * *"
  
  # Ручной запуск
  workflow_dispatch:

  # Запуск при пуше в main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      # Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Генерируем pacman contribution graph
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: QIBIK

      # Пушим результат в ветку output
      - name: Push pacman-contribution-graph.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist   # папка, куда скрипт кладет svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
